openapi: 3.0.0
info:
  version: 1.0.0
  title: 3855_api
  description: ''
paths:
  /list:
    get:
      summary: Get list of events and IDs
      operationId: app.get_mysql_event_list
      responses:
        '200':
          description: Successfully returned the list of events and IDs from mysql
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/list'
        '400':
          description: Bad Request        

  /count:
    get:
      summary: Get number of records in the database
      operationId: app.get_count
      responses:
        '200':
          description: Successfully returned the number of records in the database
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/count'
        '400':
          description: Bad Request  

  /online-orders:
    get:
      summary: Get online-order sale transactions
      operationId: app.get_online_orders
      parameters:
        - name: start_timestamp
          in: query
          required: true
          schema:
            type: string
            format: date-time
            example: '2025-01-08T09:12:33.001Z'
        - name: end_timestamp
          in: query
          required: true
          schema:
            type: string
            format: date-time
            example: '2025-01-08T09:12:33.001Z'
      responses:
        '200':
          description: Successfully returned a list of online-order sale transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/online'
        '400':
          description: Bad Request
  /store-sales:
    get:
      summary: get in-store sale transactions
      tags: []
      operationId: app.get_store_sales
      parameters:
        - name: start_timestamp
          required: true
          in: query
          schema:
            type: string
            format: date-time
            example: '2025-01-08T09:12:33.001Z'
        - name: end_timestamp
          required: true
          in: query
          schema:
            type: string
            format: date-time
            example: '2025-01-08T09:12:33.001Z'
      responses:
        '200':
          description: Successfully returned a list of in-store sale transactions history
          content:
            application/json:
              schema:
               type: array
               items:
                $ref: '#/components/schemas/instore'
        '400':
          description: Bad Request    
components:
  schemas:
    list:
      type: array
      required:
        - event_id
        - trace_id
        - type
      properties:
        event_id:
          type: string
          example: C1234
        trace_id:
          type: number
          format: integer
          example: 1674235285973157000
        type:
          type: string
          example: online_order

    count:
      type: object
      required:
        - online_order_count
        - store_sale_count
      properties:
        online_order_count:
          type: number
          format: integer
          example: 100
        store_sale_count:
          type: number
          format: integer
          example: 100

    online:
      type: object
      required:
        - cid
        - order_amount
        - shipping_address
        - order_time
        - trace_id
      properties:
        cid:
          type: string
          example: 'C1234'
        order_amount:
          type: number
          format: float
          example: 100.00
        shipping_address:
          type: string
          example: '123 ABC St, Vancouer, CA'
        order_time:
          type: string
          format: date-time
          example: '2025-01-08T09:12:33.001Z'
        trace_id:
          type: number
          example: 1674235285973157000
          
    instore:
      type: object
      required:
        - sid
        - sale_amount
        - payment_method
        - sale_time
        - trace_id
      properties:
        sid:
          type: string
          example: van01
        sale_amount:
          type: number
          format: float
          example: 33.50
        payment_method:
          type: string
          example: Cash
        sale_time:
          type: string
          example: '2025-01-08T08:12:33.001Z'
          format: date-time
        trace_id:
          #num
          type: number
          example: 1674235285973157000
          