version: 1
datastore:
  filename: /data/<service_name>/<service_name>.json
scheduler:
  interval: 5
eventstores:
  online_orders:
    url: http://dashboard/storage/online-orders
  store_sales:
    url: http://dashboard/storage/store-sales
